### ISSUE TITLE
Broken as of new URI

### ISSUE THREAD

**Issue by rdrapeau** [synthead/mint-adfree#1]
It seem's mint has changed their URI to `mint.intuit.com` instead of what used to be `mint.com`. 

I've tried to update the filters with find / replace with this change but now I can no longer login if the filter is enabled. I get the error `For your safety we logged you out after being idle for 10 minutes. Please login again.` and am immediately logged out.

**Comment by edgariscoding** [comment]
I have the same issue

**Comment by synthead** [comment]
Fixed with https://github.com/synthead/mint-adfree/commit/ec14e3daa5f3d98950ce037d5a9fa63371daf7f5 :+1:
