### ISSUE TITLE
mint.com not blocked

### ISSUE THREAD

**Issue by bigrig2212** [synthead/mint-adfree#13]
installed as per instructions - didn't seem to do anything to mint.com ads. no issues with the installation though - looks like ublock is importing correctly.

**Comment by synthead** [comment]
Hey, thank for filing this issue!

Could you take a screenshot of the ads you're seeing?  Or more information in another way?  I don't have enough information to resolve this issue.

This list is supposed to block the ads inside the Mint app when you're logged in, not on the main website.  Is this where you're seeing the ads?

**Comment by paradoxministry** [comment]
@bigrig2212 Make sure you're not Whitelisting mint.com in uBlock Origin's Whitelist settings. You can find this under uBlock Origin's settings under the Whitelist tab. Somehow I had www.mint.com already whitelisted.

**Comment by synthead** [comment]
Closing due to about six months without a response.  If this is still a bug, please re-open 👍
