### ISSUE TITLE
Doesn't support beta redesign

### ISSUE THREAD

**Issue by ankushg** [synthead/mint-adfree#19]
Looks like there's a redesign of Mint coming through: https://beta.mint.intuit.com/transactions?source=mint.intuit.com

**Comment by ankushg** [comment]
I've added these rules locally and they seem to be useful:

```
! hides many promotional messages
beta.mint.intuit.com##:xpath(//div[contains(@data-morpheus-widget, 'promotions')])

! hides marketplace recommendations from the overview page
beta.mint.intuit.com###marketplace-overview-cards

! hides bill negotiation recommendations from bills page
beta.mint.intuit.com##:xpath(//div[contains(@class, 'BillNegotiationCollapse')])
```

**Comment by synthead** [comment]
Hey thanks so much for filing this issue!

Just added beta support in 1b8e9840c963f35c8c2d6b06c84470b23235e59a and e4e2f018b82873063c93ea950754217db71ae949!

If you have any further suggestions or see something I missed, feel free to file a new issue :+1:
