### ISSUE TITLE
Mint.com Refresh

### ISSUE THREAD

**Issue by colby-makowsky** [synthead/mint-adfree#21]
It looks like Intuit has refreshed the look and feel of Mint.com and now the AdFree block list needs an overhaul!

**Comment by ankushg** [comment]
Looks like we just need to replace `beta.mint.intuit.com` with `mint.intuit.com` now that the redesign is out of beta!

**Comment by CelestialStreamer** [comment]
I changed `beta.mint.intuit.com` with `mint.intuit.com` too and that seems to have fixed everything!

**Comment by synthead** [comment]
Fixed with https://github.com/synthead/mint-adfree/pull/22, closing!
